from __future__ import annotations

from enum import Enum, auto


class EngineAction(Enum):
    START_CHAMBER = auto()
    REACH_TREATMENT_DEPTH = auto()
    LOG_COMPLETE_RELIEF_AT_60 = auto()
    LOG_NO_COMPLETE_RELIEF_AT_60 = auto()
    LOG_WORSENING_AT_60 = auto()
    SELECT_TT5 = auto()
    SELECT_TT6 = auto()
    SELECT_TT6A = auto()
    ADVANCE_SEGMENT = auto()
    ADD_EXTENSION = auto()
    LEAVE_SURFACE = auto()
    START_HOLD = auto()
    END_HOLD = auto()
    REACH_BOTTOM = auto()
    LEAVE_BOTTOM = auto()
    REACH_STOP = auto()
    LEAVE_STOP = auto()
    CONFIRM_BOTTOM_MIX = auto()
    CONFIRM_50_50 = auto()
    CONFIRM_ON_O2 = auto()
    START_AIR_BREAK = auto()
    END_AIR_BREAK = auto()
    START_DELAY = auto()
    END_DELAY = auto()
    CONVERT_TO_AIR = auto()
    SWITCH_TO_SURD = auto()
    SWITCH_TO_MIXED_GAS_SURFACE_DECOMPRESSION = auto()
    REACH_SURFACE = auto()
    LEAVE_SURFACE_INTERVAL = auto()
    REACH_CHAMBER_50 = auto()
    MOVE_CHAMBER = auto()
    COMPLETE_TO_SURFACE = auto()
    TOGGLE_OFF_O2 = auto()
    RESET = auto()
