"""Structured dive tables used by the application."""

from .air_decompression import (
    AirDecoRow,
    AirO2OxygenShiftPlan,
    BasicAirDecompressionProfile,
    BetweenStopsDelayEvaluation,
    DecompressionMode,
    FirstStopArrivalEvaluation,
    air_o2_oxygen_stop_depths,
    available_air_decompression_depths,
    available_air_o2_decompression_depths,
    available_decompression_depths,
    build_air_o2_oxygen_shift_plan,
    build_basic_air_decompression_profile,
    build_basic_air_decompression_profile_for_session,
    build_basic_air_o2_decompression_profile,
    build_basic_air_o2_decompression_profile_for_session,
    build_basic_decompression_profile,
    build_basic_decompression_profile_for_session,
    evaluate_between_stops_delay,
    evaluate_first_stop_arrival,
    lookup_air_decompression_row,
    lookup_air_o2_decompression_row,
    lookup_decompression_row,
    planned_travel_time_to_first_stop_seconds,
)
from .no_decompression import (
    NoDecompressionRow,
    lookup_no_decompression_limit,
    lookup_no_decompression_limit_for_depth,
    lookup_repetitive_group,
    lookup_repetitive_group_schedule,
)

__all__ = [
    "AirDecoRow",
    "AirO2OxygenShiftPlan",
    "BasicAirDecompressionProfile",
    "BetweenStopsDelayEvaluation",
    "DecompressionMode",
    "FirstStopArrivalEvaluation",
    "NoDecompressionRow",
    "air_o2_oxygen_stop_depths",
    "available_air_decompression_depths",
    "available_air_o2_decompression_depths",
    "available_decompression_depths",
    "build_air_o2_oxygen_shift_plan",
    "build_basic_air_decompression_profile",
    "build_basic_air_decompression_profile_for_session",
    "build_basic_air_o2_decompression_profile",
    "build_basic_air_o2_decompression_profile_for_session",
    "build_basic_decompression_profile",
    "build_basic_decompression_profile_for_session",
    "evaluate_between_stops_delay",
    "evaluate_first_stop_arrival",
    "lookup_air_decompression_row",
    "lookup_air_o2_decompression_row",
    "lookup_decompression_row",
    "lookup_no_decompression_limit",
    "lookup_no_decompression_limit_for_depth",
    "lookup_repetitive_group",
    "lookup_repetitive_group_schedule",
    "planned_travel_time_to_first_stop_seconds",
]
